language: bash
sudo:     true

before_install:
  - sudo apt-get install -y sshpass
addons:
  apt:
    update: true

after_success:
  - echo "Deploying to server..."
  # - ssh-keygen -R hostname
  - export SSHPASS=$SERVER_SECRET
  - sshpass -e scp -v -r * $SERVER_USERNAME@$SERVER_HOSTNAME:/srv/hosted_files/ubuntu/
