language: bash
sudo:     true

before_install:
  - sudo apt-get install -y sshpass
addons:
  apt:
    update: true

after_success:
  - echo "Deploying to server..."
  - sshpass -p $SERVER_SECRET scp -v -o stricthostkeychecking=no -r * $SERVER_USERNAME@$SERVER_HOSTNAME:/srv/hosted_files/ubuntu/
