language: bash
sudo:     required

service:
  - docker

before_install:
  - sudo apt-get install -y sshpass
addons:
  apt:
    update: true

script:
  - echo "Deploying to server..."
  - sshpass -p "$SERVER_SECRET" scp -v -r * $SERVER_USERNAME@$SERVER_HOSTNAME:/srv/hosted_files/ubuntu/
