language: bash
sudo:     required

service:
  - docker

before_install:
  - sudo apt-get install -y sshpass
addons:
  apt:
    update: true

script:
  - echo "Deploying to server..."
  - sshpass -p $SERVER_PASS scp -v -r * $SERVER_USER@$SERVER_NAME:/srv/hosted_files/ubuntu/
