# This is a basic workflow to help you get started with Actions

name: Deploying ubuntu shell script

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying Scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing Required Packages
      run: sudo apt-get install -y sshpass
    - name: Deploying to the server
      run: sshpass -p ${{ secrets.SERVER_SECRET }} scp -v -o stricthostkeychecking=no -r * ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }}:/srv/hosted_files/ubuntu/
    - name: Testing deployment on new server (mrinal.xyz)
      run: |
        echo ${{ secrets.SSH_PRIV_KEY }} | base64 -d > private_key
        chmod 600 private_key
        scp -v -e "ssh -oStrictHostKeyChecking=no -i private_key" -r * ${{ secrets.SERVER_USERNAME }}@mrinal.xyz:/srv/hosted_files/ubuntu
