# This is a basic workflow to help you get started with Actions

name: DEPLOY (dl.mrinal.xyz)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: deploying shell scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing dependencies
      run: sudo apt-get install -y sshpass
    - name: deploying scripts to the server
      run: sshpass -p ${{ secrets.SECRET }} scp -v -o stricthostkeychecking=no -r * ${{ secrets.USER }}@${{ secrets.HOSTNAME }}:/srv/hosted_files/ubuntu/
